version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"	# mysql 기본 port
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pastry # database 이름
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d